export const icons = {
    logo: require('../assets/icons/logo.png'),
    drawer: require('../assets/icons/drawer.png'),
    notification: require('../assets/icons/bell.png'),
    coffee: require('../assets/icons/coffee.png'),
    profit: require('../assets/icons/trend-up.png'),
    chart: require('../assets/icons/chart.png'),
    exclamation: require('../assets/icons/exclamation.png'),
    filter: require('../assets/icons/filter.png'),
    plus: require('../assets/icons/plus.png'),
    export: require('../assets/icons/download.png'),
    edit: require('../assets/icons/pencil.png'),
    box: require('../assets/icons/box.png'),
    delete: require('../assets/icons/trash.png'),
    dollar: require('../assets/icons/dollar.png'),
    percent: require('../assets/icons/percentage.png'),
    arrowRight: require('../assets/icons/right-chevron.png'),
    help: require('../assets/icons/question.png'),
    user: require('../assets/icons/person.png'),
    setting: require('../assets/icons/settings.png'),
    billing: require('../assets/icons/credit-card.png'),
    eye: require('../assets/icons/eye.png'),
    cross_eye: require('../assets/icons/crossed-eye.png'),
};
